In [7]:
import numpy as np
a0 = np.zeros((2, 3), dtype='int')
a_str = np.empty((2, 3), dtype='str')
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3], 
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]])

In [8]:
# ndim：取得最高維度
print(f"a2 的最高維度：{a2.ndim}")
# shape：取得維度
print(f"a2 的維度：{a2.shape}")
# size：元素總數
print(f"a_str 的元素總數：{a_str.size}")
# dtype：元素的 type
print(f"a2 元素的 type：{a2.dtype}")

a2 的最高維度：2
a2 的維度：(4, 3)
a_str 的元素總數：6
a2 元素的 type：int32


In [9]:
# 陣列資料處理
# 取索引 0 到 2 (不含)的元素
print(a1[0:2])

[1 2]


In [10]:
# 取索引 0 到 3 (不含)的元素
print(a2[0:3])
# 第 0~2 列，第 1 行
print(a2[0:3, 1])
# 第 1 列，第 0~1 行
print(a2[1, 0:2])
# 第 1 列，第 2 行
print(a2[1, 2])
# 第 1~最後一列，第 1~2 行
print(a2[1:, 1:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[4 5]
6
[[ 5  6]
 [ 8  9]
 [11 12]]


In [11]:
# 走訪所有元素
for num in np.nditer(a2):
    print(num, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 