In [3]:
import numpy as np
a0 = np.zeros((2, 3), dtype='int')
a_str = np.empty((2, 3), dtype='str')
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3], 
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]])

append, insert, delete 會產生新的陣列， 原陣列不會異動到
+ np.append(arr, value, axis=None)
+ np.insert(arr, obj, value, axis=None)
    + obj: index or indices before which values is inserted.
+ np.delete(arr, obj, axis=None)

In [4]:
a = np.append(a1, 9)
print(f"a: {a}")
print(f"a1: {a1}")
a_append_many = np.append(a1, (4, 5, 6))
print(a_append_many)

a: [1 2 3 9]
a1: [1 2 3]
[1 2 3 4 5 6]


In [30]:
a = np.insert(a1, 0, (8, 9))
print(f"a: {a}")
print(f"a1: {a1}")

a: [8 9 1 2 3]
a1: [1 2 3]


In [6]:
# np.delete(arr, index)
a_delete = np.delete(a1, 2)
print(a_delete)

[1 2]


axis=0：列

axis=1：行

未指定 axis 會將 array 平面化 (flattened)，視為 1 維陣列

In [7]:
a_1d = np.append(a2, [10, 11])
print(a_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 10 11]


In [8]:
# append 到 2 維陣列，也需是 2 維
a_2d = np.append(a2, [[13, 14, None]], axis=0)
print(a_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [10 11 12]
 [13 14 None]]


In [ ]:
a_2d_append_col = np.append(a2, [[0], [0], [0], [0]], axis=1)
print(a_2d_append_col)

[[ 1  2  3  0]
 [ 4  5  6  0]
 [ 7  8  9  0]
 [10 11 12  0]]


In [ ]:
arow = np.array([1, 2, 3, 4])
acol = np.transpose([arow])
acol

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
a2_append_acol = np.append(a2, np.transpose([arow]), axis=1)
a2_append_acol

array([[ 1,  2,  3,  1],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  3],
       [10, 11, 12,  4]])

In [31]:
# insert：有指定 insert 到哪一列，所以新增 1 維資料
a_2d_insert = np.insert(a2, 1, [13, 14, 15], axis=0)
print(a_2d_insert)

[[ 1  2  3]
 [13 14 15]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
a_2d_insert_col = np.insert(a2, 1, [0, 0, 0, 0], axis=1)
print(a_2d_insert_col)

[[ 1  0  2  3]
 [ 4  0  5  6]
 [ 7  0  8  9]
 [10  0 11 12]]


In [ ]:
bcol = np.array([[1, 2], 
                 [3, 4], 
                 [5, 6]])
brow = np.transpose(bcol)
brow

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
a2_delete_row = np.delete(a2, 1, axis=0)
a2_delete_row

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a2_delete_col = np.delete(a2, 1, axis=1)
a2_delete_col

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])
re_arr = arr.reshape(2, 3)
print(re_arr)
rere_arr = re_arr.reshape(3, 2)
print(rere_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [46]:
ra_arr = rere_arr.ravel()
print(ra_arr)

[1 2 3 4 5 6]
